[workspace]
members = [
    "./flutter_package/example/native/*",
    "./rust_crate",
    "./rust_crate_command",
]
resolver = "2"

[patch.crates-io]
rinf = { path = "./rust_crate" }
rinf_command = { path = "./rust_crate_command" }
