# Python scripts are used for managing code and automating tests.
# The reason we're not using shell scripts
# is because they're platform-dependent.

[tool.uv.workspace]
members = ["documentation"]

[tool.ruff]
select = ["E", "F", "N", "I", "PL"]

[tool.pyright]
typeCheckingMode = "strict"
