[package]
name = "rinf_command"
version = "7.3.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.98", features = ["full"] }
serde-reflection = "0.5.0"
quote = "1.0.38"
serde-generate = "0.28.0"
